version: '3.9'

services:
  backend:
    build: ./backend
    container_name: servicedeskai_backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - servicedeskai_net

  frontend:
    build: ./frontend
    container_name: servicedeskai_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app         # Monta tu código local dentro del contenedor
      - /app/node_modules       # Evita conflictos con dependencias locales
    working_dir: /app
    depends_on:
      - backend
    networks:
      - servicedeskai_net

  mongo:
    image: mongo:6
    container_name: servicedeskai_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - servicedeskai_net

networks:
  servicedeskai_net:

volumes:
  mongo_data:
